### PR TITLE
error icon added

### PR DESCRIPTION
**Pull request by FurryVile**
marsa !!!

### CODE REVIEW

**Comment by MarisaGaming01** [comment]
I dunno, seems pretty rushed

**Comment by FurryVile** [comment]
this took me 10 years, please

**Comment by MarisaGaming01** [comment]
Do you wanna build a CMake file?

**Comment by FurryVile** [comment]
do i?

**Comment by MarisaGaming01** [comment]
I dunno

**Comment by FurryVile** [comment]
what is dunno

**Comment by MarisaGaming01** [comment]
new error

**Pull request closed without merging**
